language: r
cache: packages
warnings_are_errors: false
notifications:
  email:
    recipients:
      - s.vissault@yahoo.fr
      - kevin.cazelles@gmail.com
  slack: leti-r:We4RUIQpzZ8vcazD9FIRt3Me

r_packages:
  - covr
  - r-cran-rcpp
  - r-cran-rcpparmadillo

after_success:
  - Rscript -e 'covr::codecov()'
