language: r
cache: packages
warnings_are_errors: false
notifications:
  email:
    recipients:
      - s.vissault@yahoo.fr
      - kevin.cazelles@gmail.com
  slack: leti-r:We4RUIQpzZ8vcazD9FIRt3Me

install:
  - ./run.sh install_aptget r-cran-rcpp r-cran-rcpparmadillo

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
