language: r
dist: trusty
cache: packages
sudo: required
warnings_are_errors: false
notifications:
  email:
    recipients:
      - s.vissault@yahoo.fr
      - kevin.cazelles@gmail.com
  slack: insileco:We4RUIQpzZ8vcazD9FIRt3Me


r_packages:
  - covr

r_github_packages:
  - jimhester/covr

before_install:
  - sudo apt-get update

after_success:
  - Rscript -e 'covr::codecov()'
  # - Rscript -e 'covr::coverall()'
