language: r
warnings_are_errors: false
sudo: required
cache: packages
notifications:
  email:
    recipients:
      - s.vissault@yahoo.fr
      - kevin.cazelles@gmail.com
      - Guillaume.Blanchet@USherbrooke.ca
    on_success: never 
  slack: insileco:We4RUIQpzZ8vcazD9FIRt3Me

matrix:
  include:
    - os: linux
      dist: trusty
      r: oldrel
      env: NOT_CRAN=false
      addons:
        apt:
          packages:
            - libgsl-dev
    - os: osx
      r: release
      env: NOT_CRAN=true
    - os: linux
      dist: bionic
      r: devel
      env: NOT_CRAN=false
      addons:
        apt:
          packages:
            - libgsl-dev
      r_github_packages:
        - r-lib/covr
      after_success:
        - Rscript -e 'covr::codecov()'
