language: r
warnings_are_errors: false
sudo: required
cache: packages
notifications:
  email:
    recipients:
      - Guillaume.Blanchet@USherbrooke.ca
    on_success: never 

matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      r: release
      env: NOT_CRAN=true
    - os: linux
      dist: bionic
      r: devel
      env: NOT_CRAN=false
      addons:
        apt:
          packages:
            - libgsl-dev
      r_github_packages:
        - r-lib/covr
      after_success:
        - Rscript -e 'covr::codecov()'
