---
title: "How to use itDNS"
author: "Kevin Cazelles and Steve Vissault"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Load the *Bartomeus* dataset

```{r loadalien, echo=F}
devtools::load_all(".")
```

```{r loaddata}
library(magrittr)
data(bartomeus)
## Let's examine this alienData object:
names(bartomeus)
```

<!-- idp <- which(as.character(bartomeus$interactPair[,1]) == "Apis mellifera") -->

<!-- idp <- which(bartomeus$traitSp$traitName=="flower_morphology")
simpleNetwork(bartomeus$interactPair) -->


# Load the *Bartomeus* dataset

```{r fitDMC, results="hide"}
## GLM
mod1 <- fitDMC(bartomeus, class='glm', family=poisson(), level='species', step=TRUE)
## Random Forest
mod2 <- fitDMC(bartomeus, class='rf', level='species')
```

# Predictions

```{r predictDMC, results="hide"}
df0 <- reshape2::dcast(bartomeus$traitSp, idSp ~ traitName)
df <- df0[which(!is.na(df0$flower_morphology)),]
ida <- which(as.character(df0$idSp) == "Apis mellifera")
df$IT <- df0$IT[ida]
df$tongue_length <- df0$tongue_length[ida]
##
names(df)[2:6] %<>% paste0(".x")
names(df)[7:8] %<>% paste0(".y")
##
for (i in 2:3) df[,i] <- as.factor(df[,i])
for (i in 4:8) df[,i] <- as.numeric(df[,i])
##
res1 <- predict.glm(mod1, newdata = df)
res2 <- predict(mod2, newdata = df)
```




# Plot the results

Here we focus on *Apis mellifera*:

<!-- ```{r fitDMC, "}
library(igraph)
idp <- which(bartomeus$traitSp$traitName=="flower_morphology")
nms <- c(as.character(bartomeus$traitSp$idSp[idp]), "Apis mellifera")
ids <- which(rownames(bartomeus$interactSp)%in%nms)
graphi <- graph_from_adjacency_matrix(bartomeus$interactSp[ids,ids])
seqtyp <- rep(1, length(nms))
seqtyp[4] <- 2
# plot(graphi,
#   vertex.size =
#   layout = layout_in_circle(graphi, c(1:3,5:57)))
``` -->


<!-- id <- which(bartomeus$traitSp$traitName=="flower_morphology")

bartomeus$idSp

plot.igraph(net,
   vertex.size = nodes$No.sources,
   vertex.color = as.factor(nodes$Type),
   vertex.frame.color= "black",
   vertex.label.color="black",
   edge.width = links$weight,
   edge.arrow.size = 1+10*log(links$weight/min(links$weight)),
   edge.color = factor(data.frame(from=links$from,
   Type=nodes[match(links$from, nodes$id),4])$Type,
   levels=levels(as.factor(nodes$Type))),
   vertex.label=NA, layout = coords, add=TRUE)
 # a loop is needed as 'srt' cannot be a vector....
 for (i in 1:length(seq.angle)) {
   text(x=title.coords[i,1], y=title.coords[i,2], nodes$Node.name[i],
   pos = title.pos[i], srt=title.angle[i], cex=0.9)
 } -->
