# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name traitsBasedJointCooc
#'
#' @title Traits-based joint co-occurrence.
#'
#' This function generates occurrence probabilities of a set of interacting
#' given for a given set of environnmental values.
#'
#' @author
#' Kevin Cazelles
#'
#' @param val a numerical vector including the environmental values.
#' @param metaweb a numerical matrix depicting the biotic interactions.
#' @param alpha a real positive number determining the importance of interactions: the
#' higher it is the more interactions impact occurrence values.
#' @param trait1 a numerical vector giving the environmental optima of species.
#' @param trait2 a optional numerical vector giving the probabilities of presence at the optimal value
#' @param trait3 a optional numerical vector giving the generalities of species.
#'
#' @return A numeric gradient x species matrix of presence probabilities of the
#' interacting species associated to the environmental values.
#'
#'
#' @examples
#' traitsBasedJointCooc(seq(-1,1,.1), webFromNicheModel(10, .1), 1, runif(10))
NULL

#' @export
traitsBasedJointCooc <- function(val, metaweb, alpha, trait1, trait2 = NULL, trait3 = NULL) {
    .Call('alienR_traitsBasedJointCooc', PACKAGE = 'alienR', val, metaweb, alpha, trait1, trait2, trait3)
}

#' @name webFromNicheModel
#'
#' @title Generate a web using the niche model.
#'
#' This function is an implementation of the niche model which generates
#' food webs based on 1- a number of species, 2- a niche axis and 3- a value of
#' comnectance.
#'
#' @author
#' Kevin Cazelles
#'
#' @param nbsp an integer giving the number of species considered.
#' @param connec a real positive between 0 and .5 indicating the connectance
#' of the network to be generated.
#' @param connec_all logical. If TRUE, then all species in the network have a
#' least one prey (but the niche with the lowest niche value).
#' @param unbias logical. If TRUE, then the first species may not be a basal species.
#' @param niche a vector real positive between 0 and 1 standing for the niche axis.
#' Default is set to \code{NULL}, in such case the niche axis is automatically generated.
#'
#' @return A logical matrix describing pairwise interactions. A given line
#' describe the diet of a given species while a column decribes the set of
#' predator accociated to a particular species.
#'
#' @details
#' Three remarks. First, according to Williams and Martinez (2000),
#' the species with the lowest niche value is considered as a basal and thus
#' has no trait. This introduces a slight bias (\emph{e.g} the
#' expected connectance is lower than the expected values \code{connec}). Second,
#' forcing all the species to be connected introduces another biais (connectance)
#' tends to be more connected than expected.
#' Third, if one uses its own customed niche axis, values should be between 0 and
#' and 1 and the expected connectance (\code{connec}) can vary significantly if the
#' distribution of niche values differ from the uniform distribution used in
#' Williams and Martinez (2000)
#'
#' @references
#' Williams, R.J. and Martinez, N.D. (2000) Simple rules yield complex food webs.
#' \emph{Nature}, 404, 180–183.
#'
#' @export
#'
webFromNicheModel <- function(nbsp, connec, connect_all = FALSE, unbias = FALSE, niche = NULL) {
    .Call('alienR_webFromNicheModel', PACKAGE = 'alienR', nbsp, connec, connect_all, unbias, niche)
}

